import type { TypographyStyle, TypographyToken } from '../core/types'

export const typography: Record<TypographyToken, TypographyStyle> = {
  headline: {
    fontFamily: 'Syne',
    fontWeight: 800,
    fontSize: 64,
    lineHeight: 72,
    letterSpacing: -1.4,
    color: 'Text',
    textAlign: 'left',
  },
  candidateName: {
    fontFamily: 'Syne',
    fontWeight: 800,
    fontSize: 66,
    lineHeight: 72,
    letterSpacing: -1.4,
    color: 'Text',
    textAlign: 'left',
  },
  candidateNumber: {
    fontFamily: 'Montserrat',
    fontWeight: 900,
    fontSize: 180,
    lineHeight: 176,
    letterSpacing: -4.2,
    color: 'Primary',
    textAlign: 'left',
  },
  hashtag: {
    fontFamily: 'Montserrat',
    fontWeight: 900,
    fontSize: 78,
    lineHeight: 84,
    letterSpacing: -0.8,
    color: 'White',
    stroke: 'Primary',
    strokeWidth: 3,
    shadow: 'none',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  header: {
    fontFamily: 'Manrope',
    fontWeight: 700,
    fontSize: 27,
    lineHeight: 34,
    letterSpacing: 0,
    color: 'Text',
    textAlign: 'left',
  },
  footer: {
    fontFamily: 'Manrope',
    fontWeight: 600,
    fontSize: 23,
    lineHeight: 30,
    letterSpacing: 0,
    color: 'MutedText',
    textAlign: 'left',
  },
  caption: {
    fontFamily: 'Manrope',
    fontWeight: 500,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0,
    color: 'MutedText',
    textAlign: 'left',
  },
  body: {
    fontFamily: 'Manrope',
    fontWeight: 600,
    fontSize: 31,
    lineHeight: 40,
    letterSpacing: 0,
    color: 'Text',
    textAlign: 'left',
  },
  party: {
    fontFamily: 'Montserrat',
    fontWeight: 800,
    fontSize: 34,
    lineHeight: 38,
    letterSpacing: 0.8,
    color: 'Accent',
    textTransform: 'uppercase',
    textAlign: 'right',
  },
}
