import type { TypographyStyle, TypographyToken } from '../core/types'

export const typography: Record<TypographyToken, TypographyStyle> = {
  headline: {
    fontFamily: 'Syne',
    fontWeight: 800,
    fontSize: 64,
    lineHeight: 72,
    letterSpacing: -1.4,
    color: 'Text',
    textAlign: 'left',
  },
  candidateName: {
    fontFamily: 'Syne',
    fontWeight: 800,
    fontSize: 76,
    lineHeight: 82,
    letterSpacing: -1.6,
    color: 'Text',
    textAlign: 'left',
  },
  candidateNumber: {
    fontFamily: 'Montserrat',
    fontWeight: 900,
    fontSize: 208,
    lineHeight: 208,
    letterSpacing: -5,
    color: 'Primary',
    textAlign: 'left',
  },
  hashtag: {
    fontFamily: 'Montserrat',
    fontWeight: 900,
    fontSize: 98,
    lineHeight: 104,
    letterSpacing: -1.4,
    color: 'White',
    stroke: 'Primary',
    strokeWidth: 6,
    shadow: 'soft',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  header: {
    fontFamily: 'Manrope',
    fontWeight: 700,
    fontSize: 27,
    lineHeight: 34,
    letterSpacing: 0,
    color: 'Text',
    textAlign: 'left',
  },
  footer: {
    fontFamily: 'Manrope',
    fontWeight: 600,
    fontSize: 23,
    lineHeight: 30,
    letterSpacing: 0,
    color: 'MutedText',
    textAlign: 'left',
  },
  caption: {
    fontFamily: 'Manrope',
    fontWeight: 500,
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0,
    color: 'MutedText',
    textAlign: 'left',
  },
  body: {
    fontFamily: 'Manrope',
    fontWeight: 600,
    fontSize: 31,
    lineHeight: 40,
    letterSpacing: 0,
    color: 'Text',
    textAlign: 'left',
  },
  party: {
    fontFamily: 'Montserrat',
    fontWeight: 800,
    fontSize: 42,
    lineHeight: 46,
    letterSpacing: 1.2,
    color: 'Accent',
    textTransform: 'uppercase',
    textAlign: 'right',
  },
}
