import type { TemplateNode } from '../../core/types'

export const supportFrameNodes: TemplateNode[] = [
  {
    id: 'background-gradient',
    kind: 'shape',
    region: 'SafeArea',
    fill: 'Surface',
    radius: 'xl',
    border: 'regular',
    stroke: 'Border',
    shadow: 'soft',
    opacity: 0.94,
  },
  {
    id: 'candidate-photo',
    kind: 'image',
    region: 'PhotoArea',
    source: 'brand.candidatePhoto',
    fit: 'cover',
    radius: 'lg',
    border: 'strong',
    borderColor: 'White',
    shadow: 'elevated',
    mask: 'rounded',
  },
  {
    id: 'frame-overlay',
    kind: 'image',
    region: 'PhotoArea',
    source: 'brand.frame',
    fit: 'cover',
    radius: 'lg',
    mask: 'rounded',
    opacity: 0.35,
  },
  {
    id: 'logo-badge',
    kind: 'shape',
    region: 'LogoArea',
    fill: 'Primary',
    radius: 'pill',
  },
  {
    id: 'brand-logo',
    kind: 'image',
    region: 'LogoArea',
    source: 'brand.logo',
    fit: 'contain',
    radius: 'pill',
    mask: 'rounded',
  },
  {
    id: 'candidate-avatar',
    kind: 'image',
    region: 'UserPhotoArea',
    source: 'brand.userPhoto',
    fit: 'cover',
    radius: 'pill',
    border: 'regular',
    borderColor: 'Surface',
    shadow: 'soft',
    mask: 'circle',
    opacity: 0.96,
  },
  {
    id: 'side-logo-top',
    kind: 'image',
    region: 'SideLogoTopArea',
    source: 'brand.logo',
    fit: 'contain',
    radius: 'md',
    mask: 'rounded',
  },
  {
    id: 'side-logo-bottom',
    kind: 'image',
    region: 'SideLogoBottomArea',
    source: 'brand.secondaryLogo',
    fit: 'contain',
    radius: 'md',
    mask: 'rounded',
  },
  {
    id: 'top-left-text',
    kind: 'text',
    region: 'TopLeftTextArea',
    source: 'content.topLeftText',
    typography: 'header',
    component: 'header',
    horizontalAlign: 'left',
    verticalAlign: 'middle',
    autoFit: true,
    maxLines: 1,
    ellipsis: true,
    minFontSize: 14,
  },
  {
    id: 'top-right-text',
    kind: 'text',
    region: 'TopRightTextArea',
    source: 'content.topRightText',
    typography: 'header',
    component: 'header',
    horizontalAlign: 'right',
    verticalAlign: 'middle',
    autoFit: true,
    maxLines: 1,
    ellipsis: true,
    minFontSize: 14,
  },
  {
    id: 'hashtag',
    kind: 'text',
    region: 'HashtagArea',
    source: 'content.hashtag',
    typography: 'hashtag',
    component: 'hashtag',
    horizontalAlign: 'center',
    verticalAlign: 'middle',
    autoFit: true,
    maxLines: 3,
    ellipsis: false,
    minFontSize: 18,
  },
  {
    id: 'candidate-name',
    kind: 'text',
    region: 'CandidateArea',
    source: 'content.candidateName',
    typography: 'candidateName',
    component: 'candidateName',
    horizontalAlign: 'left',
    verticalAlign: 'middle',
    autoFit: true,
    maxLines: 2,
    ellipsis: true,
    minFontSize: 28,
  },
  {
    id: 'experience-name',
    kind: 'text',
    region: 'ExperienceNameArea',
    source: 'name',
    typography: 'caption',
    component: 'footer',
    horizontalAlign: 'right',
    verticalAlign: 'middle',
    autoFit: true,
    maxLines: 1,
    ellipsis: true,
    minFontSize: 12,
  },
  {
    id: 'candidate-number',
    kind: 'text',
    region: 'NumberArea',
    source: 'content.candidateNumber',
    typography: 'candidateNumber',
    component: 'candidateNumber',
    horizontalAlign: 'left',
    verticalAlign: 'middle',
    autoFit: true,
    maxLines: 1,
    ellipsis: false,
    minFontSize: 56,
  },
  {
    id: 'party',
    kind: 'text',
    region: 'PartyArea',
    source: 'content.party',
    typography: 'party',
    horizontalAlign: 'right',
    verticalAlign: 'middle',
    autoFit: true,
    maxLines: 1,
    ellipsis: true,
    uppercase: true,
  },
  {
    id: 'footer-text',
    kind: 'text',
    region: 'FooterArea',
    source: 'content.bottomLine1',
    typography: 'footer',
    component: 'footer',
    horizontalAlign: 'left',
    verticalAlign: 'middle',
    autoFit: true,
    maxLines: 1,
    ellipsis: true,
    minFontSize: 13,
  },
  {
    id: 'footer-text-line2',
    kind: 'text',
    region: 'FooterLine2Area',
    source: 'content.bottomLine2',
    typography: 'caption',
    component: 'footer',
    horizontalAlign: 'left',
    verticalAlign: 'middle',
    autoFit: true,
    maxLines: 1,
    ellipsis: true,
    minFontSize: 12,
  },
]
