import type { ExperienceTemplateConfig } from '../../core/types'
import { buildSupportFrameRegionLayout } from './support-frame.layout'

const supportFrameRegionLayout = buildSupportFrameRegionLayout(true)

export const supportFrameRegions: ExperienceTemplateConfig['regions'] = {
  HeaderArea: {
    enabled: true,
    order: 1,
    layout: supportFrameRegionLayout.HeaderArea,
    nodes: [
      {
        id: 'header-surface',
        kind: 'shape',
        fill: 'Surface',
        stroke: 'Border',
        border: 'thin',
        radius: 'md',
      },
    ],
  },
  LogoLeftArea: {
    enabled: true,
    order: 2,
    layout: supportFrameRegionLayout.LogoLeftArea,
    nodes: [
      {
        id: 'logo-left',
        kind: 'image',
        source: 'brand.logo',
        fit: 'contain',
        cropMode: 'center',
      },
    ],
  },
  LogoRightArea: {
    enabled: true,
    order: 3,
    layout: supportFrameRegionLayout.LogoRightArea,
    nodes: [
      {
        id: 'logo-right',
        kind: 'image',
        source: 'brand.logoSecondary',
        fit: 'contain',
        cropMode: 'center',
      },
    ],
  },
  PhotoArea: {
    enabled: true,
    order: 4,
    layout: supportFrameRegionLayout.PhotoArea,
    nodes: [
      {
        id: 'photo-frame-surface',
        kind: 'shape',
        fill: 'Surface',
        stroke: 'Border',
        border: 'regular',
        radius: 'xl',
        shadow: 'soft',
      },
      {
        id: 'main-candidate-photo',
        kind: 'image',
        source: 'brand.candidatePhoto',
        fit: 'cover',
        cropMode: 'smart',
        radius: 'lg',
        border: 'strong',
        borderColor: 'White',
        shadow: 'elevated',
        mask: 'rounded',
      },
    ],
  },
  OverlayArea: {
    enabled: true,
    order: 5,
    layout: supportFrameRegionLayout.OverlayArea,
    nodes: [
      {
        id: 'photo-overlay-frame',
        kind: 'image',
        source: 'brand.frame',
        fit: 'cover',
        cropMode: 'center',
        radius: 'lg',
        mask: 'rounded',
        opacity: 0.18,
      },
    ],
  },
  HashtagArea: {
    enabled: true,
    order: 6,
    layout: supportFrameRegionLayout.HashtagArea,
    nodes: [
      {
        id: 'hashtag',
        kind: 'text',
        source: 'content.hashtag',
        typography: 'hashtag',
        component: 'hashtag',
        horizontalAlign: 'center',
        verticalAlign: 'middle',
        autoFit: true,
        maxLines: 3,
        ellipsis: false,
        minFontSize: 18,
      },
    ],
  },
  FooterArea: {
    enabled: true,
    order: 7,
    layout: supportFrameRegionLayout.FooterArea,
    nodes: [
      {
        id: 'footer-surface',
        kind: 'shape',
        fill: 'Surface',
        stroke: 'Border',
        border: 'regular',
        radius: 'xl',
        shadow: 'soft',
      },
    ],
  },
  FooterLine1Area: {
    enabled: true,
    order: 8,
    layout: supportFrameRegionLayout.FooterLine1Area,
    nodes: [
      {
        id: 'footer-text-line1',
        kind: 'text',
        source: 'content.bottomLine1',
        typography: 'footer',
        component: 'footer',
        horizontalAlign: 'left',
        verticalAlign: 'middle',
        autoFit: true,
        maxLines: 1,
        ellipsis: true,
        minFontSize: 14,
      },
    ],
  },
  FooterLine2Area: {
    enabled: true,
    order: 9,
    layout: supportFrameRegionLayout.FooterLine2Area,
    nodes: [
      {
        id: 'footer-text-line2',
        kind: 'text',
        source: 'content.bottomLine2',
        typography: 'caption',
        component: 'footer',
        horizontalAlign: 'left',
        verticalAlign: 'middle',
        autoFit: true,
        maxLines: 2,
        ellipsis: true,
        minFontSize: 12,
      },
      {
        id: 'footer-party',
        kind: 'text',
        source: 'content.party',
        typography: 'party',
        horizontalAlign: 'left',
        verticalAlign: 'bottom',
        autoFit: true,
        maxLines: 1,
        ellipsis: true,
        minFontSize: 14,
        uppercase: true,
      },
    ],
  },
  CandidateNumberArea: {
    enabled: true,
    order: 10,
    layout: supportFrameRegionLayout.CandidateNumberArea,
    nodes: [
      {
        id: 'candidate-number',
        kind: 'text',
        source: 'content.candidateNumber',
        typography: 'candidateNumber',
        component: 'candidateNumber',
        horizontalAlign: 'left',
        verticalAlign: 'middle',
        autoFit: true,
        maxLines: 1,
        ellipsis: false,
        minFontSize: 52,
      },
    ],
  },
  CandidatePhotoArea: {
    enabled: true,
    order: 11,
    layout: supportFrameRegionLayout.CandidatePhotoArea,
    nodes: [
      {
        id: 'candidate-photo-footer-surface',
        kind: 'shape',
        fill: 'White',
        stroke: 'Border',
        border: 'thin',
        radius: 'xl',
        shadow: 'soft',
      },
      {
        id: 'candidate-photo-footer',
        kind: 'image',
        source: 'brand.candidatePhoto',
        fit: 'cover',
        cropMode: 'smart',
        radius: 'lg',
        border: 'thin',
        borderColor: 'White',
        shadow: 'soft',
        mask: 'rounded',
      },
    ],
  },
}
